name: Create Release
description: Tags a repository and creates a GitHub Release.

outputs:
  version:
    description: Version number for the newly created release.
    value: ${{ steps.semver.outputs.version }}

runs:
  using: "composite"
  steps:
    - id: semver
      name: Calculate version
      uses: ./.github/actions/git-version-provider

    - name: Tag repository
      run: |
        git tag "${{ steps.semver.outputs.version }}"
        git push origin "${{ steps.semver.outputs.version }}"
      shell: bash
  
    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@v1.0.0
      with:
        myToken: ${{ runner.token }}
 
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ steps.changelog.outputs.changelog }}
        tag_name: v${{ steps.semver.outputs.version }}
