name: Load Docker Image
description: Loads a Docker image that was saved by a previous job as a workflow artifact.

inputs:
  artifact:
    description: Name of the uploaded artifact containing the image.
    default: image
    required: false

outputs:
  tag:
    description: The first tag contained in the loaded image.
    value: ${{ steps.set-metadata.outputs.tag }}
  repository:
    description: Repository name for the loaded image.
    value: ${{ steps.set-metadata.outputs.repository }}
  tags:
    description: JSON string containing an array of all tags for the loaded image.
    value: ${{ steps.set-metadata.outputs.tags }}

runs:
  using: "composite"
  steps:
    - name: Download
      id: download
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.artifact }}
        path: ${{ runner.temp }}

    - name: Load
      run: |
        docker load --input "${{ steps.download.outputs.download-path }}/image.tar"
      shell: sh

    - id: set-metadata
      name: Set metadata outputs
      run: |
        REPOSITORY=$(cat "${{ steps.download.outputs.download-path }}/metadata.json" | jq -cr '.tags[0] | split(":")[0]')
        TAG=$(cat "${{ steps.download.outputs.download-path }}/metadata.json" | jq -cr '.tags[0]')
        TAGS=$(cat "${{ steps.download.outputs.download-path }}/metadata.json" | jq -c '.tags')
        echo "::set-output name=repository::${REPOSITORY}"
        echo "::set-output name=tag::${TAG}"
        echo "::set-output name=tags::${TAGS}"
      shell: bash