name: Git Version Provider
description: Version provider that calculates a semantic version based solely on git tags.

outputs:
  version:
    description: Calculated semantic version for this build.
    value: ${{ steps.semver.outputs.version }}

runs:
  using: "composite"
  steps:
    - uses: paulhatch/semantic-version@v4.0.2
      id: semver
      name: Calculate version
      with:
        tag_prefix: "v"
        format: "${major}.${minor}.${patch}"