name: Build and Validate Image

on:
  workflow_call:
    inputs:
      image-name:
        description: Name of the container image to build.
        default: ${{ github.repository }}
        type: string

env:
  CONTAINER_IMAGE: ghcr.io/${{ inputs.image-name }}
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract image metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.CONTAINER_IMAGE }}
          tags: |
            type=edge,branch=main
            type=ref,event=branch
            type=ref,event=tag
            type=schedule
            type=sha,format=long,prefix=

      - name: Build image
        id: build
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
        with:
          context: ./container
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=${{ runner.temp }}/image.tar
          tags: ${{ steps.meta.outputs.tags }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: image
          path: ${{ runner.temp }}/image.tar

