name: Validate Pull Request
on:
  pull_request: 
    paths:
      - .github/**
      - container/**

jobs:
  build:
    name: Build
    uses: 'skleinjung/devcontainers/.github/workflows/build-and-validate-image.yml@semver-test-branch'

  test-load:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: ./.github/actions/load-docker-image
        with:
          artifact-name: image 